from __future__ import annotations

import time
from datetime import datetime, timezone
from typing import Literal
from uuid import UUID, uuid4

from typing import Annotated

from pydantic import BaseModel, BeforeValidator, Field, model_validator

from .enums import OrderType, Side


class Order(BaseModel):
    id: UUID = Field(default_factory=uuid4)
    pod_id: str
    symbol: str
    side: Side
    order_type: OrderType
    quantity: float = Field(gt=0)
    limit_price: float | None = None
    timestamp: datetime
    strategy_tag: str  # pod-internal, never exposed cross-boundary
    conviction: float = 0.5
    model_config = {"frozen": True}


class Fill(BaseModel):
    id: UUID = Field(default_factory=uuid4)
    order_id: UUID
    pod_id: str
    symbol: str
    side: Side
    quantity: float
    price: float
    commission: float
    timestamp: datetime
    model_config = {"frozen": True}


class Position(BaseModel):
    pod_id: str
    symbol: str
    quantity: float
    avg_cost: float
    market_value: float
    unrealised_pnl: float
    last_updated: datetime


class RejectedOrder(BaseModel):
    order_id: UUID
    reason: str
    timestamp: datetime = Field(default_factory=datetime.now)


class RiskApprovalToken(BaseModel):
    pod_id: str
    order_id: UUID
    issued_at_ms: float = Field(default_factory=lambda: time.time() * 1000)
    expires_ms: float = 500.0

    def is_valid(self) -> bool:
        return (time.time() * 1000 - self.issued_at_ms) < self.expires_ms


class OrderResult(BaseModel):
    """Result of order execution on Alpaca."""
    order_id: str | None
    symbol: str
    qty: float
    side: Literal["buy", "sell"]
    status: Literal["FILLED", "PARTIAL", "REJECTED", "PENDING"]
    fill_price: float | None
    fill_qty: float
    reason: str | None = None
    stage: str | None = None
    filled_at: datetime | None = None


def _clamp_01(v: float) -> float:
    return max(0.0, min(1.0, float(v)))


ClampedFloat = Annotated[float, BeforeValidator(_clamp_01)]


SpecialistType = Literal[
    "macro_policy",
    "trend_technical",
    "risk_skeptic",
    "positioning_flows",
    "asset_fundamental",
    "crypto_onchain",
    "commodity_supply_demand",
    "fx_rates_policy",
]


class CatalystEvent(BaseModel):
    """Advisory impact event generated by the Foresight layer."""

    event_id: str
    thread_id: str = ""
    title: str
    summary: str = ""
    source_refs: list[dict] = Field(default_factory=list)
    novelty_score: ClampedFloat = 0.5
    impact_score: ClampedFloat = 0.5
    confidence: ClampedFloat = 0.5
    materiality_score: ClampedFloat = 0.5
    affected_pods: list[str] = Field(default_factory=list)
    affected_symbols: list[str] = Field(default_factory=list)
    factors: list[str] = Field(default_factory=list)
    direction: str = "mixed"
    horizon: str = "days"
    horizon_start: datetime | None = None
    horizon_end: datetime | None = None
    transmission_path: str = ""
    uncertainty: str = ""
    routing_reason: dict[str, str] = Field(default_factory=dict)
    suggested_specialists: list[str] = Field(default_factory=list)
    status: str = "active"
    linked_run_ids: list[str] = Field(default_factory=list)
    linked_report_ids: list[str] = Field(default_factory=list)
    linked_trade_ids: list[str] = Field(default_factory=list)
    outcome_score: float | None = None
    hindsight_score: float | None = None
    reviewed_at: datetime | None = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class SpecialistRequest(BaseModel):
    """PM request for a bounded specialist analysis brief."""

    type: SpecialistType
    symbol: str = ""
    question: str
    reason: str = ""
    related_catalyst_ids: list[str] = Field(default_factory=list)
    decision_impact: str = ""
    required_data: str = ""


class SpecialistBrief(BaseModel):
    """Advisory specialist response fed back into the PM."""

    brief_id: str
    type: SpecialistType
    symbol: str = ""
    question: str = ""
    conclusion: str = ""
    supporting_evidence: list[str] = Field(default_factory=list)
    opposing_evidence: list[str] = Field(default_factory=list)
    confidence: ClampedFloat = 0.5
    invalidation: str = ""
    source_refs: list[dict] = Field(default_factory=list)
    related_catalyst_ids: list[str] = Field(default_factory=list)
    data_used: list[str] = Field(default_factory=list)
    missing_data: list[str] = Field(default_factory=list)
    decision_impact: str = ""
    hindsight_score: float | None = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class CommitteeReview(BaseModel):
    """Pre-trade reasoning gate before hard risk/execution controls."""

    review_id: str
    pod_id: str
    symbol: str
    side: str
    decision: Literal["APPROVE", "REVISE", "REJECT"] = "APPROVE"
    reason: str = ""
    reviewers: list[dict] = Field(default_factory=list)
    reviewer_votes: list[dict] = Field(default_factory=list)
    blockers: list[str] = Field(default_factory=list)
    revision_fields: list[str] = Field(default_factory=list)
    hindsight_score: float | None = None
    confidence: ClampedFloat = 0.5
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class DecisionSnapshot(BaseModel):
    """Sanitized, replayable context captured at a final PM decision."""

    snapshot_id: str
    decision_id: str = ""
    pod_id: str
    symbol: str = ""
    side: str = "HOLD"
    status: str = "active"
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    decision_horizon: str = "days"
    horizon_end: datetime | None = None
    price_at_decision: float | None = None
    position_state: dict = Field(default_factory=dict)
    catalyst_ids: list[str] = Field(default_factory=list)
    catalyst_state: list[dict] = Field(default_factory=list)
    signal_features: dict = Field(default_factory=dict)
    specialist_briefs: list[dict] = Field(default_factory=list)
    committee_review: dict = Field(default_factory=dict)
    thesis_fields: dict = Field(default_factory=dict)
    risk_state: dict = Field(default_factory=dict)
    artifact_status: dict = Field(default_factory=dict)
    model_trace_refs: list[str] = Field(default_factory=list)
    report_refs: list[str] = Field(default_factory=list)


class DecisionEvaluation(BaseModel):
    """Outcome review for a stored decision snapshot."""

    evaluation_id: str
    snapshot_id: str
    pod_id: str = ""
    symbol: str = ""
    side: str = "HOLD"
    evaluated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    horizon_met: bool = False
    price_at_decision: float | None = None
    price_at_evaluation: float | None = None
    return_pct: float | None = None
    pnl: float | None = None
    pnl_pct: float | None = None
    outcome: str = "unknown"
    score: ClampedFloat = 0.5
    notes: list[str] = Field(default_factory=list)
    missing_data: list[str] = Field(default_factory=list)
    report_id: str = ""


class ShadowReplayResult(BaseModel):
    """Dry-run comparison between an original decision and current logic."""

    replay_id: str
    snapshot_id: str
    pod_id: str = ""
    symbol: str = ""
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    original_decision: dict = Field(default_factory=dict)
    replay_decision: dict = Field(default_factory=dict)
    changed: bool = False
    comparison: str = ""
    dry_run: bool = True
    state_mutation_detected: bool = False
    execution_attempted: bool = False
    report_id: str = ""


class PortfolioConstructionReview(BaseModel):
    """Advisory portfolio-construction gate before hard risk/execution."""

    review_id: str
    pod_id: str
    symbol: str
    side: str
    requested_notional: float = 0.0
    recommended_notional: float = 0.0
    action: Literal["APPROVE_SIZE", "DOWNSIZE", "TRIM_TO_FUND", "SKIP_DUPLICATIVE", "REQUEST_PM_REVISION"] = "APPROVE_SIZE"
    reason: str = ""
    duplicate_exposures: list[str] = Field(default_factory=list)
    portfolio_impact: dict = Field(default_factory=dict)
    funding_suggestion: str = ""
    expected_factor_change: dict = Field(default_factory=dict)
    confidence: ClampedFloat = 0.5
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class InstrumentProfile(BaseModel):
    """Tradeable instrument profile used for exposure-first reasoning."""

    symbol: str
    name: str = ""
    asset_class: str = ""
    tradable: bool = True
    broker_symbol: str = ""
    primary_factor: str = "unclassified"
    factor_loadings: dict[str, float] = Field(default_factory=dict)
    instrument_role: str = ""
    liquidity_notes: str = ""
    cost_notes: str = ""
    known_risks: list[str] = Field(default_factory=list)
    substitutes: list[str] = Field(default_factory=list)
    preferred_when: list[str] = Field(default_factory=list)
    avoid_when: list[str] = Field(default_factory=list)
    last_reviewed_at: datetime | None = None
    source: str = "static"


class ThesisMonitorResult(BaseModel):
    """Live review of whether an open-position thesis still holds."""

    monitor_id: str
    pod_id: str
    symbol: str
    status: Literal["THESIS_OK", "REVIEW_REQUIRED", "ADD_BLOCKED", "REDUCE_RECOMMENDED", "EXIT_RECOMMENDED"] = "THESIS_OK"
    reason: str = ""
    triggers: list[str] = Field(default_factory=list)
    catalyst_ids: list[str] = Field(default_factory=list)
    thesis_age_days: float | None = None
    max_hold_days: int = 0
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    report_id: str = ""


class CalibrationScore(BaseModel):
    """Advisory calibration score for sources, specialists, reviewers, factors, and thesis patterns."""

    entity_type: str
    entity_id: str
    pod_id: str = ""
    factor: str = ""
    sample_size: int = 0
    hit_rate: float = 0.0
    avg_forward_return: float = 0.0
    avg_pnl: float = 0.0
    false_positive_rate: float = 0.0
    false_negative_rate: float = 0.0
    confidence: ClampedFloat = 0.5
    last_updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


def _pct_fraction(v: float) -> float:
    n = float(v)
    if n > 1.0 and n <= 100.0:
        n = n / 100.0
    return n


PositivePct = Annotated[float, BeforeValidator(_pct_fraction), Field(gt=0.0)]
FractionPct = Annotated[float, BeforeValidator(_pct_fraction), Field(gt=0.0, le=1.0)]


class TakeProfitLevel(BaseModel):
    """One optional scale-out level for a position.

    `trigger_pct` and `close_pct` are decimal fractions: 0.08 means +8% and
    0.25 means close 25% of the then-open position.
    """

    trigger_pct: PositivePct
    close_pct: FractionPct = 0.25
    trail_stop_pct: PositivePct | None = None
    label: str = ""

    @model_validator(mode="before")
    @classmethod
    def normalize_aliases(cls, data):
        if not isinstance(data, dict):
            return data
        out = dict(data)
        if "trigger_pct" not in out:
            out["trigger_pct"] = (
                out.get("pct")
                or out.get("profit_pct")
                or out.get("target_pct")
                or out.get("take_profit_pct")
            )
        if "close_pct" not in out:
            out["close_pct"] = (
                out.get("exit_pct")
                or out.get("qty_pct")
                or out.get("close_fraction")
                or out.get("fraction")
            )
        return out


class TradeProposal(BaseModel):
    """Validated trade proposal from LLM output. Rejects malformed trades."""
    action: Literal["BUY", "SELL"]
    symbol: str
    qty: float = Field(gt=0)
    reasoning: str = ""
    conviction: ClampedFloat = 0.5
    strategy_tag: str = ""
    signal_snapshot: dict = Field(default_factory=dict)
    stop_loss_pct: float = 0.05
    take_profit_pct: float = 0.15
    take_profit_levels: list[TakeProfitLevel] = Field(default_factory=list)
    exit_when: str = ""
    max_hold_days: int = 0


class PositionSnapshot(BaseModel):
    """Snapshot of an open position with current market data."""
    symbol: str
    qty: float  # Positive = long, negative = short
    cost_basis: float  # Average cost per share
    current_price: float  # Current market price
    unrealized_pnl: float  # qty * (current_price - cost_basis)
    entry_thesis: str = ""
    entry_date: str = ""
    stop_loss_pct: float = 0.05
    take_profit_pct: float = 0.15
    take_profit_levels: list[dict] = Field(default_factory=list)
    take_profit_hits: list[int] = Field(default_factory=list)
    max_hold_days: int = 0
    conviction: float = 0.0
    thesis_status: str = "unknown"
    thesis_issues: list[str] = Field(default_factory=list)
    thesis_review: dict = Field(default_factory=dict)
    evidence_packet: dict = Field(default_factory=dict)
    price_source: str = ""
    price_updated_at: str = ""
    price_stale: bool = False

    @property
    def notional(self) -> float:
        """Notional value of position at current price."""
        return self.qty * self.current_price

    @property
    def current_notional(self) -> float:
        """Current market value of the position."""
        return self.qty * self.current_price

    @property
    def entry_notional(self) -> float:
        """Original cost-basis value of the current open quantity."""
        return self.qty * self.cost_basis

    @property
    def pnl_pct(self) -> float:
        """PnL as percentage of cost basis."""
        if self.cost_basis == 0:
            return 0.0
        return (self.current_price - self.cost_basis) / self.cost_basis * 100


class VerificationResult(BaseModel):
    """Result from ThesisVerifier quality check on a PM trade decision."""
    passed: bool
    quality_score: float  # 0–1; above 0.5 passes
    feedback: str = ""  # actionable critique when not passed


class DiscoveredTicker(BaseModel):
    """A ticker discovered via theme scanning. Persisted across sessions."""
    symbol: str
    theme: str                          # e.g. "AI Infrastructure"
    thesis: str                         # Why this ticker was added
    discovered_date: str                # ISO date string e.g. "2026-04-14"
    next_review_date: str               # ISO date string — when to re-validate thesis
    status: str = "active"             # "active" | "inactive"
    invalidation_reason: str | None = None
    source_headlines: list[str] = []    # Headlines that triggered discovery


class PodPosition(BaseModel):
    """Position model exposed in PodSummary (crosses pod boundary)."""
    symbol: str
    qty: float
    current_price: float
    unrealized_pnl: float = 0.0
    notional: float = 0.0  # qty * current_price
    cost_basis: float = 0.0
    entry_date: str = ""
    entry_thesis: str = ""
    stop_loss_pct: float = 0.05
    take_profit_pct: float = 0.15
    take_profit_levels: list[dict] = Field(default_factory=list)
    take_profit_hits: list[int] = Field(default_factory=list)
    max_hold_days: int = 0
    conviction: float = 0.0
    thesis_status: str = "unknown"
    thesis_issues: list[str] = Field(default_factory=list)
    thesis_review: dict = Field(default_factory=dict)
    evidence_packet: dict = Field(default_factory=dict)
    price_source: str = ""
    price_updated_at: str = ""
    price_stale: bool = False
